Switch to erofs

diff --git a/board/rgarc/init b/board/rgarc/init
--- a/board/rgarc/init
+++ b/board/rgarc/init
@@ -16,21 +16,21 @@ while ! ls -l /dev/mmcblk1p1 > /dev/null; do
     sleep 1
 done
 
-mkdir -p /boot /squash /overlay /mnt
+mkdir -p /boot /root_fs /overlay /mnt
 
 mount /dev/mmcblk1p1 /boot
 
 mkdir -p /boot/update
 
-for f in rootfs.squashfs Image initrd.gz; do
+for f in rootfs.erofs Image initrd.gz; do
     if [ -f /boot/update/$f ]; then
         mv /boot/update/$f /boot/
     fi
 done
 echo -n "r" > /dev/tty1
 
-mount -t squashfs /boot/rootfs.squashfs /squash \
-    || (echo "Failed to mount squashfs")
+mount -t erofs /boot/rootfs.erofs /root_fs \
+    || (echo "Failed to mount rootfs" > /dev/tty1)
 
 mount -o noatime /dev/mmcblk1p2 /overlay \
     || (echo "Failed to mount /dev/mmcblk1p2")
@@ -50,7 +50,7 @@ if [ "$reset" -eq 10 ]; then
 fi
 
 echo -n "r" > /dev/tty1
-mount -t overlay root_overlay -o lowerdir=/squash,upperdir=/overlay/overlay,workdir=/overlay/work /mnt
+mount -t overlay root_overlay -o lowerdir=/root_fs,upperdir=/overlay/overlay,workdir=/overlay/work /mnt
 
 mount --move /boot /mnt/boot
 mount --move /proc /mnt/proc
